In [2]:
pip install numpy

Requirement already satisfied: numpy in c:\users\yasht\appdata\roaming\python\python312\site-packages (2.5.3)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
from scipy import stats

df = pd.read_csv(
    r"D:\my career\Zomato market analysis\Datasets\processed\zomato_featured.csv"
)

df.shape

(9551, 26)

Create the two groups

In [4]:
online_delivery_yes = df.loc[
    df["Has Online delivery"] == "Yes", "Votes"
]

online_delivery_no = df.loc[
    df["Has Online delivery"] == "No", "Votes"
]

online_delivery_yes.shape, online_delivery_no.shape

((2451,), (7100,))

Calculate group means

In [5]:
online_delivery_yes.mean(), online_delivery_no.mean()

(np.float64(211.30722154222767), np.float64(138.13112676056338))

Statistical test

In [6]:
t_stat, p_value = stats.ttest_ind(
    online_delivery_yes,
    online_delivery_no,
    equal_var=False
)

t_stat, p_value

(np.float64(6.593556960801556), np.float64(4.914380648074537e-11))

Online Delivery vs Votes

In [7]:
test_results = pd.DataFrame({
    "Test": ["Online Delivery vs Votes"],
    "Group 1": ["Online Delivery = Yes"],
    "Group 2": ["Online Delivery = No"],
    "Mean 1": [online_delivery_yes.mean()],
    "Mean 2": [online_delivery_no.mean()],
    "t_statistic": [t_stat],
    "p_value": [p_value],
    "Significant": [p_value < 0.05]
})

test_results

,Test,Group 1,Group 2,Mean 1,Mean 2,t_statistic,p_value,Significant
0,Online Delivery vs Votes,Online Delivery = Yes,Online Delivery = No,211.307222,138.131127,6.593557,4.914381e-11,True

Table Booking vs Rating

In [8]:
table_booking_yes = df.loc[
    df["Has Table booking"] == "Yes", "Aggregate rating"
]

table_booking_no = df.loc[
    df["Has Table booking"] == "No", "Aggregate rating"
]

table_booking_yes.shape, table_booking_no.shape

((1158,), (8393,))

group means

In [9]:
table_booking_yes.mean(), table_booking_no.mean()

(np.float64(3.4419689119170984), np.float64(2.559358989634219))

two-sample t-test

In [10]:
t_stat_2, p_value_2 = stats.ttest_ind(
    table_booking_yes,
    table_booking_no,
    equal_var=False
)

t_stat_2, p_value_2

(np.float64(28.508665862732638), np.float64(2.2173812053434623e-153))

Table Booking vs Rating

In [11]:
test_results.loc[len(test_results)] = {
    "Test": "Table Booking vs Rating",
    "Group 1": "Table Booking = Yes",
    "Group 2": "Table Booking = No",
    "Mean 1": table_booking_yes.mean(),
    "Mean 2": table_booking_no.mean(),
    "t_statistic": t_stat_2,
    "p_value": p_value_2,
    "Significant": p_value_2 < 0.05
}

test_results

,Test,Group 1,Group 2,Mean 1,Mean 2,t_statistic,p_value,Significant
0,Online Delivery vs Votes,Online Delivery = Yes,Online Delivery = No,211.307222,138.131127,6.593557,4.914381e-11,True
1,Table Booking vs Rating,Table Booking = Yes,Table Booking = No,3.441969,2.559359,28.508666,2.217381e-153,True

In [12]:
import os

os.makedirs(
    r"D:\my career\Zomato market analysis\Reports",
    exist_ok=True
)

test_results.to_csv(
    r"D:\my career\Zomato market analysis\Reports\statistical_results.csv",
    index=False
)

In [13]:
import pandas as pd

df = pd.read_csv(
    r"D:\my career\Zomato market analysis\Datasets\processed\zomato_featured.csv"
)

df.shape

(9551, 26)